repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black

repos:
  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3  # Use the latest version
    hooks:
      - id: pylint
        args: ["--rcfile=.pylintrc"]  # Use custom config file

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
