import numpy as np
from numpy import sqrt

from python_propagate.Scenario import Scenario
from python_propagate.Dynamics import Dynamic
from python_propagate.Agents.state import State

# TODO: explore specifying the difference between the classes for normal dynamics and STMs


class STM(Dynamic):

    def __init__(self, scenario: Scenario, agent=None, stm=True):
        super().__init__(scenario, agent, stm)

    def function(self, state: State, time: float):

        stm = state.stm
        A_matrix = self.A_matrix(state)

        stm_dot = A_matrix @ stm

        return State(stm_dot=stm_dot, time=time)

    def A_matrix(self, state: State):

        rx, ry, rz = state.extract_position()
        vx, vy, vz = state.extract_velocity()

        r = np.sqrt(rx**2 + ry**2 + rz**2)

        R = self.scenario.central_body.radius
        mu = self.scenario.central_body.mu
        J2 = self.scenario.central_body.J2
        J3 = self.scenario.central_body.J3

        rho0, h0, H = self.scenario.central_body.atmosphere_model(r)
        Cd = self.agent.coefficet_of_drag
        area = self.agent.area
        mass = self.agent.mass
        angular_velocity = self.scenario.central_body.angular_velocity

        # automatically generated by sympy
        a_matrix_total = np.array(
            [
                [0, 0, 0, 1, 0, 0],
                [0, 0, 0, 0, 1, 0],
                [0, 0, 0, 0, 0, 1],
                [
                    500000000.0
                    * area
                    * Cd
                    * rho0
                    * angular_velocity
                    * (-rx * angular_velocity + vy)
                    * (ry * angular_velocity + vx)
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    )
                    + 500000000.0
                    * area
                    * Cd
                    * rho0
                    * rx
                    * (ry * angular_velocity + vx)
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (H * mass * sqrt(rx**2 + ry**2 + rz**2))
                    - 21
                    / 2
                    * J2
                    * R**2
                    * mu
                    * rx**2
                    * (-(rx**2) - ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    - 3 * J2 * R**2 * mu * rx**2 / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    + (3 / 2)
                    * J2
                    * R**2
                    * mu
                    * (-(rx**2) - ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    - 45
                    / 2
                    * J3
                    * R**3
                    * mu
                    * rx**2
                    * rz
                    * (-3 * rx**2 - 3 * ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (11 / 2)
                    - 15
                    * J3
                    * R**3
                    * mu
                    * rx**2
                    * rz
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + (5 / 2)
                    * J3
                    * R**3
                    * mu
                    * rz
                    * (-3 * rx**2 - 3 * ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 3 * mu * rx**2 / (rx**2 + ry**2 + rz**2) ** (5 / 2)
                    - mu / (rx**2 + ry**2 + rz**2) ** (3 / 2),
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * angular_velocity
                    * (ry * angular_velocity + vx) ** 2
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    )
                    - 500000000.0
                    * area
                    * Cd
                    * rho0
                    * angular_velocity
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / mass
                    + 500000000.0
                    * area
                    * Cd
                    * rho0
                    * ry
                    * (ry * angular_velocity + vx)
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (H * mass * sqrt(rx**2 + ry**2 + rz**2))
                    - 21
                    / 2
                    * J2
                    * R**2
                    * mu
                    * rx
                    * ry
                    * (-(rx**2) - ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    - 3 * J2 * R**2 * mu * rx * ry / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    - 45
                    / 2
                    * J3
                    * R**3
                    * mu
                    * rx
                    * ry
                    * rz
                    * (-3 * rx**2 - 3 * ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (11 / 2)
                    - 15
                    * J3
                    * R**3
                    * mu
                    * rx
                    * ry
                    * rz
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 3 * mu * rx * ry / (rx**2 + ry**2 + rz**2) ** (5 / 2),
                    500000000.0
                    * area
                    * Cd
                    * rho0
                    * rz
                    * (ry * angular_velocity + vx)
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (H * mass * sqrt(rx**2 + ry**2 + rz**2))
                    - 21
                    / 2
                    * J2
                    * R**2
                    * mu
                    * rx
                    * rz
                    * (-(rx**2) - ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 12 * J2 * R**2 * mu * rx * rz / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    - 45
                    / 2
                    * J3
                    * R**3
                    * mu
                    * rx
                    * rz**2
                    * (-3 * rx**2 - 3 * ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (11 / 2)
                    + 20
                    * J3
                    * R**3
                    * mu
                    * rx
                    * rz**2
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + (5 / 2)
                    * J3
                    * R**3
                    * mu
                    * rx
                    * (-3 * rx**2 - 3 * ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 3 * mu * rx * rz / (rx**2 + ry**2 + rz**2) ** (5 / 2),
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * (ry * angular_velocity + vx) ** 2
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    )
                    - 500000000.0
                    * area
                    * Cd
                    * rho0
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / mass,
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * (-rx * angular_velocity + vy)
                    * (ry * angular_velocity + vx)
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    ),
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * vz
                    * (ry * angular_velocity + vx)
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    ),
                ],
                [
                    500000000.0
                    * area
                    * Cd
                    * rho0
                    * angular_velocity
                    * (-rx * angular_velocity + vy) ** 2
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    )
                    + 500000000.0
                    * area
                    * Cd
                    * rho0
                    * angular_velocity
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / mass
                    + 500000000.0
                    * area
                    * Cd
                    * rho0
                    * rx
                    * (-rx * angular_velocity + vy)
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (H * mass * sqrt(rx**2 + ry**2 + rz**2))
                    - 21
                    / 2
                    * J2
                    * R**2
                    * mu
                    * rx
                    * ry
                    * (-(rx**2) - ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    - 3 * J2 * R**2 * mu * rx * ry / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    - 45
                    / 2
                    * J3
                    * R**3
                    * mu
                    * rx
                    * ry
                    * rz
                    * (-3 * rx**2 - 3 * ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (11 / 2)
                    - 15
                    * J3
                    * R**3
                    * mu
                    * rx
                    * ry
                    * rz
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 3 * mu * rx * ry / (rx**2 + ry**2 + rz**2) ** (5 / 2),
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * angular_velocity
                    * (-rx * angular_velocity + vy)
                    * (ry * angular_velocity + vx)
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    )
                    + 500000000.0
                    * area
                    * Cd
                    * rho0
                    * ry
                    * (-rx * angular_velocity + vy)
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (H * mass * sqrt(rx**2 + ry**2 + rz**2))
                    - 21
                    / 2
                    * J2
                    * R**2
                    * mu
                    * ry**2
                    * (-(rx**2) - ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    - 3 * J2 * R**2 * mu * ry**2 / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    + (3 / 2)
                    * J2
                    * R**2
                    * mu
                    * (-(rx**2) - ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    - 45
                    / 2
                    * J3
                    * R**3
                    * mu
                    * ry**2
                    * rz
                    * (-3 * rx**2 - 3 * ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (11 / 2)
                    - 15
                    * J3
                    * R**3
                    * mu
                    * ry**2
                    * rz
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + (5 / 2)
                    * J3
                    * R**3
                    * mu
                    * rz
                    * (-3 * rx**2 - 3 * ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 3 * mu * ry**2 / (rx**2 + ry**2 + rz**2) ** (5 / 2)
                    - mu / (rx**2 + ry**2 + rz**2) ** (3 / 2),
                    500000000.0
                    * area
                    * Cd
                    * rho0
                    * rz
                    * (-rx * angular_velocity + vy)
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (H * mass * sqrt(rx**2 + ry**2 + rz**2))
                    - 21
                    / 2
                    * J2
                    * R**2
                    * mu
                    * ry
                    * rz
                    * (-(rx**2) - ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 12 * J2 * R**2 * mu * ry * rz / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    - 45
                    / 2
                    * J3
                    * R**3
                    * mu
                    * ry
                    * rz**2
                    * (-3 * rx**2 - 3 * ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (11 / 2)
                    + 20
                    * J3
                    * R**3
                    * mu
                    * ry
                    * rz**2
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + (5 / 2)
                    * J3
                    * R**3
                    * mu
                    * ry
                    * (-3 * rx**2 - 3 * ry**2 + 4 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 3 * mu * ry * rz / (rx**2 + ry**2 + rz**2) ** (5 / 2),
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * (-rx * angular_velocity + vy)
                    * (ry * angular_velocity + vx)
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    ),
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * (-rx * angular_velocity + vy) ** 2
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    )
                    - 500000000.0
                    * area
                    * Cd
                    * rho0
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / mass,
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * vz
                    * (-rx * angular_velocity + vy)
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    ),
                ],
                [
                    500000000.0
                    * area
                    * Cd
                    * rho0
                    * vz
                    * angular_velocity
                    * (-rx * angular_velocity + vy)
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    )
                    + 500000000.0
                    * area
                    * Cd
                    * rho0
                    * rx
                    * vz
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (H * mass * sqrt(rx**2 + ry**2 + rz**2))
                    - 21
                    / 2
                    * J2
                    * R**2
                    * mu
                    * rx
                    * rz
                    * (-3 * rx**2 - 3 * ry**2 + 2 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    - 9 * J2 * R**2 * mu * rx * rz / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    - 45
                    / 2
                    * J3
                    * R**3
                    * mu
                    * rx
                    * (
                        7 * rz**4
                        + (0.6 * rx**2 + 0.6 * ry**2 - 5.4 * rz**2)
                        * (rx**2 + ry**2 + rz**2)
                    )
                    / (rx**2 + ry**2 + rz**2) ** (11 / 2)
                    + (5 / 2)
                    * J3
                    * R**3
                    * mu
                    * (
                        2 * rx * (0.6 * rx**2 + 0.6 * ry**2 - 5.4 * rz**2)
                        + 1.2 * rx * (rx**2 + ry**2 + rz**2)
                    )
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 3 * mu * rx * rz / (rx**2 + ry**2 + rz**2) ** (5 / 2),
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * vz
                    * angular_velocity
                    * (ry * angular_velocity + vx)
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    )
                    + 500000000.0
                    * area
                    * Cd
                    * rho0
                    * ry
                    * vz
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (H * mass * sqrt(rx**2 + ry**2 + rz**2))
                    - 21
                    / 2
                    * J2
                    * R**2
                    * mu
                    * ry
                    * rz
                    * (-3 * rx**2 - 3 * ry**2 + 2 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    - 9 * J2 * R**2 * mu * ry * rz / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    - 45
                    / 2
                    * J3
                    * R**3
                    * mu
                    * ry
                    * (
                        7 * rz**4
                        + (0.6 * rx**2 + 0.6 * ry**2 - 5.4 * rz**2)
                        * (rx**2 + ry**2 + rz**2)
                    )
                    / (rx**2 + ry**2 + rz**2) ** (11 / 2)
                    + (5 / 2)
                    * J3
                    * R**3
                    * mu
                    * (
                        2 * ry * (0.6 * rx**2 + 0.6 * ry**2 - 5.4 * rz**2)
                        + 1.2 * ry * (rx**2 + ry**2 + rz**2)
                    )
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 3 * mu * ry * rz / (rx**2 + ry**2 + rz**2) ** (5 / 2),
                    500000000.0
                    * area
                    * Cd
                    * rho0
                    * rz
                    * vz
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (H * mass * sqrt(rx**2 + ry**2 + rz**2))
                    - 21
                    / 2
                    * J2
                    * R**2
                    * mu
                    * rz**2
                    * (-3 * rx**2 - 3 * ry**2 + 2 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 6 * J2 * R**2 * mu * rz**2 / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    + (3 / 2)
                    * J2
                    * R**2
                    * mu
                    * (-3 * rx**2 - 3 * ry**2 + 2 * rz**2)
                    / (rx**2 + ry**2 + rz**2) ** (7 / 2)
                    - 45
                    / 2
                    * J3
                    * R**3
                    * mu
                    * rz
                    * (
                        7 * rz**4
                        + (0.6 * rx**2 + 0.6 * ry**2 - 5.4 * rz**2)
                        * (rx**2 + ry**2 + rz**2)
                    )
                    / (rx**2 + ry**2 + rz**2) ** (11 / 2)
                    + (5 / 2)
                    * J3
                    * R**3
                    * mu
                    * (
                        28 * rz**3
                        + 2 * rz * (0.6 * rx**2 + 0.6 * ry**2 - 5.4 * rz**2)
                        - 10.8 * rz * (rx**2 + ry**2 + rz**2)
                    )
                    / (rx**2 + ry**2 + rz**2) ** (9 / 2)
                    + 3 * mu * rz**2 / (rx**2 + ry**2 + rz**2) ** (5 / 2)
                    - mu / (rx**2 + ry**2 + rz**2) ** (3 / 2),
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * vz
                    * (ry * angular_velocity + vx)
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    ),
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * vz
                    * (-rx * angular_velocity + vy)
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    ),
                    -500000000.0
                    * area
                    * Cd
                    * rho0
                    * vz**2
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / (
                        mass
                        * sqrt(
                            vz**2
                            + (-rx * angular_velocity + vy) ** 2
                            + (ry * angular_velocity + vx) ** 2
                        )
                    )
                    - 500000000.0
                    * area
                    * Cd
                    * rho0
                    * sqrt(
                        vz**2
                        + (-rx * angular_velocity + vy) ** 2
                        + (ry * angular_velocity + vx) ** 2
                    )
                    * np.exp((R + h0 - sqrt(rx**2 + ry**2 + rz**2)) / H)
                    / mass,
                ],
            ]
        )

        return a_matrix_total
