# name: Black Code Formatter

# on: [push, pull_request]

# jobs:
#   black:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install Poetry
#         uses: abatilo/actions-poetry@v2
#       - name: Install Dependencies
#         run: poetry install
#       - name: Run Black
#         run: poetry run black --check .
